### ISSUE TITLE
Unable to pip install the package

### ISSUE THREAD

**Issue by 0tist** [cybergalactic/PythonVehicleSimulator#6]
Created a conda env with pytthon version = 3.9.5
ran the following command: `pip install -e ./PythonVehicleSimulator`

```
Obtaining file:///Users/jayeshvasudeva/Development/GitHub/PythonVehicleSimulator
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting matplotlib
  Using cached matplotlib-3.6.2-cp39-cp39-macosx_10_12_x86_64.whl (7.3 MB)
Collecting pytest
  Using cached pytest-7.2.0-py3-none-any.whl (316 kB)
Collecting numpy
  Using cached numpy-1.24.1-cp39-cp39-macosx_10_9_x86_64.whl (19.8 MB)
ERROR: Package 'python-vehicle-simulator' requires a different Python: 3.9.5 not in '>=3.10'
```
Changed python_requires parameter in setup.cfg to:
`python_requires = 3.9.5`
because of the above error, then got this output:
```
Obtaining file:///Users/jayeshvasudeva/Development/GitHub/PythonVehicleSimulator
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/_vendor/packaging/specifiers.py", line 634, in __init__
          parsed.add(Specifier(specifier))
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/_vendor/packaging/specifiers.py", line 98, in __init__
          raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
      setuptools.extern.packaging.specifiers.InvalidSpecifier: Invalid specifier: '3.9.5 #>=3.10'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/jayeshvasudeva/miniconda3/envs/MAS/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/jayeshvasudeva/miniconda3/envs/MAS/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/jayeshvasudeva/miniconda3/envs/MAS/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 179, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 451, in prepare_metadata_for_build_editable
          return self.prepare_metadata_for_build_wheel(
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 863, in parse_config_files
          setupcfg.parse_configuration(
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py", line 162, in parse_configuration
          options.parse()
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py", line 496, in parse
          section_parser_method(section_options)
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py", line 470, in parse_section
          self[name] = value
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py", line 278, in __setitem__
          value = parser(value)
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/_vendor/packaging/specifiers.py", line 636, in __init__
          parsed.add(LegacySpecifier(specifier))
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/_vendor/packaging/specifiers.py", line 253, in __init__
          super().__init__(spec, prereleases)
        File "/private/var/folders/p2/d3pv89wj5kj8yqqsgwg3ns5r0000gn/T/pip-build-env-a913z21n/overlay/lib/python3.9/site-packages/setuptools/_vendor/packaging/specifiers.py", line 98, in __init__
          raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
      setuptools.extern.packaging.specifiers.InvalidSpecifier: Invalid specifier: '3.9.5 #>=3.10'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by cybergalactic** [comment]
You need to use python >=3.10 or remove the switch statements on line 50 in the main.py file, that is

match no:                       #  the match statement requires Python >= 3.10
    case '1': vehicle = DSRV('depthAutopilot',60.0)
    case '2': vehicle = frigate('headingAutopilot',10.0,100.0)
    case '3': vehicle = otter('headingAutopilot',100.0,0.3,-30.0,200.0)  
    case '4': vehicle = ROVzefakkel('headingAutopilot',3.0,100.0)
    case '5': vehicle = semisub('DPcontrol',10.0,10.0,40.0,0.5,190.0)
    case '6': vehicle = shipClarke83('headingAutopilot',-20.0,70,8,6,0.7,0.5,10.0,1e5)
    case '7': vehicle = supply('DPcontrol',4.0,4.0,100.0,0.5,20.0)
    case '8': vehicle = tanker('headingAutopilot',-20,0.5,150,20,80)
    case '9': vehicle = remus100('depthHeadingAutopilot',30,50,1525,0.5,170)     
    case _: print('Error: Not a valid simulator option'), sys.exit()

Python 3.9.5 does not support this command.

**Comment by 0tist** [comment]
Seems like #428, made another environment witch explicit python=3.10.9
that seems to have solved the problem.
Thanks
